config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # get 'board/show'
  get 'boards/show', to: 'board#list'
  get 'boards/show/:id', to: 'board#show', as: "board"

  namespace :users do
    get 'manage', to: 'manage#show'
    get 'manage/edit/:id', to: "manage#edit"
    patch 'manage/update'
  end

  namespace :game do
    get 'list'
    post 'join/:id', action: :join, as: "join"
    post 'leave/:id', action: :leave, as: "leave"
    get 'new'
    post 'create'
    get 'play/:id', action: :play
  end

  mount ActionCable.server, at: '/cable'

  # Defines the root path route ("/")
  root "home#index"
end

app/models/game.rb
class Game < ApplicationRecord
  include SqidLink

  has_many :game_users
  has_many :users, through: :game_users
  belongs_to :board

  validates :board_id, :title, presence: true

  enum :game_status, [ :pending, :in_progress, :complete ], default: :pending
  enum :visiblity, [ :visible, :hidden ], default: :visible

  scope :joinable, -> { where(:game_status => :pending) }
  scope :running, -> { where(:game_status => :in_progress) }
  scope :visible, -> { where(:visiblity => :visible) }
  scope :browseable, -> { visible.joinable }
  scope :joined, ->(user) { select { |game| user.joined?(game) } }
  scope :not_joined, ->(user) { select { |game| !user.joined?(game) } }

  def add_player(player)
    self.user_ids = self.user_ids.push(player.id).uniq
    player_state = self.game_users.find_by(user_id: player.id)
    player_state.board = JSON.parse(self.board.json)
    player_state.save
  end

  def add_players(players)
    players.each {|player| add_player(player)}
  end

  def remove_player(player)
    self.user_ids = self.user_ids - [player.id]
  end

  def remove_players(players)
    players.each {|player| add_player(player)}
  end
end

app/controllers/game_controller.rb
class GameController < ApplicationController
  before_action :check_user

  def new
    @board = Board.find_by(id: params[:board_id])
  end

  def create
    game =  Game.new
    game.board_id = params[:board][:id]
    game.title = params[:title]
    if game.save
      game.add_player(current_user)
      flash[:alert] = nil
      redirect_to action: "play", id: game.id
    else
      flash[:alert] = "Error: " + game.errors.full_messages.join(", ")
      render :new, status: :unprocessable_entity
    end
  end

  def join
    game = Game.find(params[:id])
    if current_user.can_join?(game)
      game.add_player(current_user)
      redirect_to action: "play", id: game.id
    else
      flash[:alert] = "Error: Can not join game"
      render :new, status: :unprocessable_entity
    end
  end

  def leave
    game = Game.find(params[:id])
    if current_user.joined?(game)
      game.remove_player(current_user)
      redirect_to root_path
    else
      flash[:alert] = "Error: Already unenrolled from this game"
      render :new, status: :unprocessable_entity
    end
  end

  def list
    @browseable = Game.browseable.not_joined(current_user)
    @joined = Game.joined(current_user)
  end

  def play
    @game = Game.find(params[:id])
    if !current_user.joined?(@game)
      flash[:alert] = "Error: Not enrolled in selected game"
      redirect_to root_path
    end
  end

  private

  def check_user
    if current_user.nil?
      flash[:alert] = "You do not have permission to access that page"
      redirect_to root_path
    end
  end
end

app/helpers/game_helper.rb
module GameHelper
  include ActionView::Helpers::FormOptionsHelper

  def board_title_form_elements(board)
    if board.nil?
      return board_form_elements
    else
      return board_from_url_elements(board)
    end
  end

  def join_button(game)
    if current_user.can_join?(game)
      link_button game_join_path(game), "Join", "user-plus", method: "post"
    elsif current_user.joined?(game)
      link_button game_path(game), "Resume", "dice"
    end
  end

  def leave_button(game, pending_only:false)
    if current_user.joined?(game) && !(!pending_only && game.pending)
      link_button game_leave_path(game), "Leave", "user-minus", method: "post"
    end
  end

  private
  def board_from_url_elements(board)
    out = ''
    out << "Board: "
    out << board.title
    out << '<input name="board[id]" type="hidden" value="'
    out << board.id.to_s
    out << '">'
    out.html_safe
  end

  def board_form_elements
    out = ''
    out << "Board: "
    out << select(:board, :id, Board.all.map {|b| [ b.title, b.id ]})
    out.html_safe
  end
end

app/views/game/_game_table.html.erb
<table class="table table-skinny table-striped table-hover">
    <thead>
        <tr>
            <th scope="col">Game</th>
            <th scope="col">Board</th>
            <th scope="col">Created</th>
            <th scope="col">Players</th>
            <th scope="col"></th>
            <th scope="col"></th>
        </tr>
    </thead>
    <tbody>
        <% game_collection.each do |game| %>
        <tr>
            <td><%= game.title %></td>
            <td><%= link_to game.board.title, board_path(game.board) %></td>
            <td><%= game.created_at %></td>
            <td><%= game.users.length %></td>
            <td><%= join_button(game) %></td>
            <td><%= leave_button(game, pending_only: true) %></td>
        </tr>
        <% end %>
    </tbody>
</table>

app/views/game/list.html.erb
<% content_for :content do %>
    <div data-controller="game_list">
        <%= render partial: "game_table", locals: {game_collection: @browseable } %>
        <%= render partial: "game_table", locals: {game_collection: @joined } %>
    </div>
<% end %>
<% content_for :right_nav do %>
<% end %>

app/views/game/new.html.erb
<h1>Game#new</h1>
<p>Find me in app/views/game/new.html.erb</p>
<%= form_with url: game_create_path, method: :post do |form| %>
    <p><%= board_title_form_elements(@board) %></p>
    <p><%= form.label :title, "Game name" %>
    <%= form.text_field :title %></p>
    <%= form.submit %>
<% end %>

app/views/game/play.html.erb
<% content_for :content do %>
    <div data-controller="game"
        data-game-board-id-value="<%= @game.board_id %>"
        data-game-game-id-value="<%= @game.to_param %>"
    >
        <svg id="svgarea" width=960 height=720 class="boardsvg" xmlns="http://www.w3.org/2000/svg"></svg>
    </div>
<% end %>
<% content_for :right_nav do %>
    <div id="info_box" style="overflow-wrap: break-word;">
<% end %>