config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # get 'board/show'
  get 'boards/show', to: 'board#list'
  get 'boards/show/:id', to: 'board#show', as: "board"

  namespace :users do
    get 'manage', to: 'manage#show'
    get 'manage/edit/:id', to: "manage#edit"
    patch 'manage/update'
  end

  namespace :game do
    get 'list'
    post 'join/:id', action: :join, as: "join"
    post 'leave/:id', action: :leave, as: "leave"
    get 'new'
    post 'create'
    get 'play/:id', action: :play
  end

  mount ActionCable.server, at: '/cable'

  # Defines the root path route ("/")
  root "home#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dice</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <div class="container-fluid min-vh-100 d-flex flex-column">
      <div class="row flex-grow-1">
        <div class="col-md-9 view_container">
          <%= content_for?(:content) ? yield(:content) : yield %>
        </div>
        <div class="col-md-3 right_nav">
          <% if user_signed_in? %>
            <p>Welcome <%= current_user.email %></p>
            <%= link_button destroy_user_session_path, "Sign out", "sign-out", method: :delete %>
          <% else %>
            <%= link_button new_user_session_path, "Sign in", "sign-in" %>
          <% end %>
          <%= link_button root_path, "Home", "home" %>
          <% if user_signed_in? %>
            <%= link_button game_list_path, "Browse Games", "dice" %>
          <% end %>
          <%= link_button boards_show_path, "Browse Boards", "map" %>
          <%= yield :right_nav %>
        </div>
      </div>
    </div>
  </body>
</html>